name-template: "v$RESOLVED_VERSION 🌈"

template: |
  ## 변경사항

  $CHANGES

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
      - "refactor"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

autolabeler: # PR에 자동으로 label 붙혀주는 규칙
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/i"
      - "/refactor/i"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
      - "/hotfix/i"
      - "/bug/i"
  - label: "feature"
    title:
      - "/feat/i"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
