template: |
  ## 변경사항

  $CHANGES

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
      - "refactor"
  - title: " Update"
    label: "⬆️ update"
  - title: "📦 Release"
    label: "update"

autolabeler:
  - label: "maintenance"
    branch:
      - '/chore\/.+/'
      - '/refactor\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "update"
    branch:
      - '/update\/.+/'
  - label: "release"
    branch:
      - '/release\/.+/'
