name: create sync PR

on:
  release:
    types: [published]

jobs:
  create_pr:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Environment Variables
        run: |
          if [ ${{ github.actor }} = "leekh716" ]; then
            echo REVIEWER="rhiokim" >> $GITHUB_ENV
          else
            echo REVIEWER="leekh716" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "main"
          title: "develop main sync up after release"
          assignee: ${{ github.actor }}
          reviewer: ${{ env.REVIEWER }}
          new_string: ${{ github.event.commits[0].message }}
          get_diff: false
