name: Create PR on Push

on:
  push:
    branches:
      - "release/*/*"

jobs:
  create_pr:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")
          PACKAGE_NAME=$(echo $BRANCH_NAME | cut -d/ -f2)
          RELEASE_VERSION=$(echo $BRANCH_NAME | cut -d/ -f3)
          PR_TITLE=":package:release/$PACKAGE_NAME/$RELEASE_VERSION staging 배포"
          ASSIGNEE=github.event.commits[0].author.name

          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Create Pull Request
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "'"$PR_TITLE"'",
              "head": "'"$BRANCH_NAME"'",
              "base": "main",
              "assignees": ["'"$ASSIGNEE"'"],
            }' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls"
