name: Create PR on Push

on:
  push:
    branches:
      - "release/*/*"
      - "sync/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_type: ${{ steps.branch.outputs._2 }}
      package_name: ${{ steps.branch.outputs._3 }}
      release_version: ${{ steps.branch.outputs._4 }}
    name: Set Variables
    steps:
      - uses: ebrain-lab/split-by@master
        id: branch
        with:
          string: ${{ github.ref }}
          split-by: "/"

  create_release_pr:
    if: ${{ needs.setup.outputs.branch_type == 'release' }}
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Reset main branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release/${{ needs.setup.outputs.package_name }}/${{ needs.setup.outputs.release_version }}
          title: ":package:release/${{ needs.setup.outputs.package_name }}/${{ needs.setup.outputs.release_version }} staging 배포"
          assignees: ${{ github.actor }}
          commit-message: ${{ github.event.commits[0].message }}
          delete-branch: true

  create_sync_pr:
    if: ${{ needs.setup.outputs.branch_type == 'sync' }}
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: sync/${{ needs.setup.outputs.package_name }}
          title: ":arrows_counterclockwise: develop main sync up"
          assignees: ${{ github.actor }}
          commit-message: ${{ github.event.commits[0].message }}
          delete-branch: true
