name: Create PR on Push

on:
  push:
    branches:
      - "release/*/*"
      - "sync/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_type: ${{ steps.branch.outputs._2 }}
      package_name: ${{ steps.branch.outputs._3 }}
      release_version: ${{ steps.branch.outputs._4 }}
    name: Set Variables
    steps:
      - uses: ebrain-lab/split-by@master
        id: branch
        with:
          string: ${{ github.ref }}
          split-by: "/"

  create_release_pr:
    if: ${{ needs.setup.outputs.branch_type == 'release' }}
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "main"
          title: ":package:release/${{ needs.setup.outputs.package_name }}/${{ needs.setup.outputs.release_version }} staging 배포"
          assignee: ${{ github.actor }}
          new_string: ${{ github.event.commits[0].message }}
          get_diff: false

  create_sync_pr:
    if: ${{ needs.setup.outputs.branch_type == 'sync' }}
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "develop"
          title: ":arrows_counterclockwise: develop main sync up"
          assignee: ${{ github.actor }}
          new_string: ${{ github.event.commits[0].message }}
          get_diff: false
