name: Create PR on Push

on:
  push:
    branches:
      - "release/*/*"

jobs:
  create_pr:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Environment Variables
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")
          PACKAGE_NAME=$(echo $BRANCH_NAME | cut -d/ -f2)
          RELEASE_VERSION=$(echo $BRANCH_NAME | cut -d/ -f3)
          PR_TITLE=":package:release/$PACKAGE_NAME/$RELEASE_VERSION staging 배포"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          if [ ${{ github.actor }} = "leekh716" ]; then
            echo REVIEWER="rhiokim" >> $GITHUB_ENV
          else
            echo REVIEWER="leekh716" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "main"
          title: ${{ env.PR_TITLE }}
          assignee: ${{ github.actor }}
          reviewer: ${{ env.REVIEWER }}
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
