name: Create PR on Push

on:
  push:
    branches:
      - "release/*/*"

jobs:
  create_pr:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")
          PACKAGE_NAME=$(echo $BRANCH_NAME | cut -d/ -f2)
          RELEASE_VERSION=$(echo $BRANCH_NAME | cut -d/ -f3)
          PR_TITLE=":package:release/$PACKAGE_NAME/$RELEASE_VERSION staging 배포"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      # - name: Get Author
      #   id: get_author
      #   run: echo "::set-output name=author::${{ toJson(github.event.commits[0].author.name) }}"

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: $PR_TITLE
          assignee: ${{ github.event.commits[0].author.name }}
          label: automatic,feature
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "**Write you description here**"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
          target_branch: "main"
